config/routes.rb
Rails.application.routes.draw do

  root 'search#index'

  get '/search/(:index)' => 'search#show', :as => 'search'
  get '/facets/(:index)' => 'search#facets', :as => 'facets'
  get '/counts/(:index)' => 'search#counts', :as => 'counts'
  get '/answers/(:index)' => 'search#answers', :as => 'answers'
  post '/preferences' => 'pages#preferences', :as => 'preferences'

  get '/healthcheck' => 'application#healthcheck'

  get 'login' => 'pages#login', :as => 'login'
  get 'logout' => 'pages#logout', :as => 'logout'
  post 'auth' => 'pages#auth', :as => 'auth'

  get '/privacy' => 'pages#privacy', :as => 'privacy'
  post '/feedback' => 'pages#feedback', :as => 'feedback'

end

app/views/pages/login.html.slim
.view-hero
  .wrapper
    div style="display: flex; justify-content: center; margin-bottom: 80px;"
      div style="margin: 0 auto;"
        h1 style="margin-bottom: 0;" Login
        = form_tag auth_path do
          input.form-control placeholder="Login" type="text" name="login"
          input.form-control placeholder="Password" type="password" name="password"
          input.btn.btn-block type="submit" value="Submit" style="margin: 0 20px 10px 0;"
          small = link_to 'Cancel', root_path

app/views/pages/privacy.html.slim
.view-hero
  .wrapper
    .hero-search.search-container style="margin-bottom: 80px;"
      h1 Privacy Policy
      p Information you provide is collected and stored. For example, anytime you search, filter, or navigate around this website, we collect and store information contained in those behaviors.
      p This website is for demonstration purposes only, and does not allow users to sign up for an account.
      p When you access or use this website, we automatically collect information about you, including:
      ul style="color: #8B9BAD;"
        li Browser type
        li IP address
        li Device information
        li Operating system & version
        li Search queries & filters
      p We use this information to improve the demo.
      p = link_to 'Back', :back, style: 'color: #8B9BAD; text-decoration: underline;'