config/routes.rb
Rails.application.routes.draw do

  root 'search#index'

  get '/search/(:index)' => 'search#show', :as => 'search'
  get '/facets/(:index)' => 'search#facets', :as => 'facets'
  get '/counts/(:index)' => 'search#counts', :as => 'counts'
  get '/answers/(:index)' => 'search#answers', :as => 'answers'
  post '/preferences' => 'pages#preferences', :as => 'preferences'

  get '/healthcheck' => 'application#healthcheck'

  get 'login' => 'pages#login', :as => 'login'
  get 'logout' => 'pages#logout', :as => 'logout'
  post 'auth' => 'pages#auth', :as => 'auth'

  get '/privacy' => 'pages#privacy', :as => 'privacy'
  post '/feedback' => 'pages#feedback', :as => 'feedback'

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Elastic Search
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = csrf_meta_tags
    = csp_meta_tag
    script src="https://unpkg.com/@elastic/apm-rum/dist/bundles/elastic-apm-rum.umd.min.js" crossorigin
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta name="apple-mobile-web-app-capable" content="yes"
    link rel="shortcut icon" href="#{asset_path 'Path@20.png'}"
    link rel="apple-touch-icon" href="#{asset_path 'Path@58.png'}"
    link rel="apple-touch-icon" sizes="76x76" href="#{asset_path 'Path@76.png'}"
    link rel="apple-touch-icon" sizes="120x120" href="#{asset_path 'Path@120.png'}"
    link rel="apple-touch-icon" sizes="152x152" href="#{asset_path 'Path@152.png'}"
  body.view-home.view-index
    .global-container
      .global-header
        #myModal.modal
          span.close-modal &times;
          img#img01.modal-content
          #caption
        .wrapper
          a.brand#logo href="/" style="text-decoration: none;"
            img src="#{asset_path @logo}"
          nav.utility-nav
            = link_to '#', class: "open-menu"
              span.app-icon style="font-size: 1.2em; opacity: 0.6;"
                i.bi.bi-grid-3x3-gap
            a.contact-support-control data-open-support="" href=""
              span.app-icon style="font-size: 1.3em; opacity: 0.8;"
                i.bi.bi-chat-dots
            - if session[:user]
              = link_to logout_path, data: { confirm: 'Logout?' }
                span.app-icon style="font-size: 1.3em; opacity: 0.6; margin-left: 10px;"
                  i.bi.bi-box-arrow-right
            - else
              = link_to login_path
                span.app-icon style="font-size: 1.3em; opacity: 0.6; margin-left: 10px;"
                  i.bi.bi-person-circle
      main.view-container
        .view-content
          = yield
      .support-callout
        .title
          - if @count
            span style="font-weight: bold; font-size: 1.5em;" = number_with_delimiter(@count, delimiter: ",")
            | &nbsp;documents
        - if request.path != '/privacy'
          .privacy style='margin: 20px 0 40px 0; opacity: 0.5;'
            = link_to 'Privacy Policy', privacy_path
    #launchpad
	    .content
		    nav
			    a class="icon-analyze" href="https://kibana.corp-intranet.com/app/discover" Discover
			    a class="icon-apm" href="https://kibana.corp-intranet.com/app/apm" APM
			    a class="icon-beats" href="https://kibana.corp-intranet.com/app/ingestManager" Beats
			    a class="icon-kibana" href="https://kibana.corp-intranet.com" Kibana
			    a class="icon-logging" href="https://kibana.corp-intranet.com/app/logs" Logs
			    a class="icon-metrics" href="https://kibana.corp-intranet.com/app/metrics" Metrics
			    a class="icon-logstash" href="https://kibana.corp-intranet.com/app/management/ingest/pipelines" Logstash
			    a class="icon-maps" href="https://kibana.corp-intranet.com/app/maps" Maps
			    a class="icon-observability" href="https://kibana.corp-intranet.com/app/observability" Observability
			    a class="icon-security" href="https://kibana.corp-intranet.com/app/security/overview" Security
			    a class="icon-stack" href="https://kibana.corp-intranet.com/app/monitoring" Monitoring
			    a class="icon-uptime" href="https://kibana.corp-intranet.com/app/uptime" Uptime
    .contact-support-container
      .wrapper
        .support-info
          h2.title Ask Search Team
          p.description
            | Can't find something?
            br
            | Tell us and we'll look into it.
          - if current_user
            a.toggle-preferences Preferences
            .toggles
              .preference
                label.switch
                  input type="checkbox"
                  span.slider.round
                span style="position: relative; top: 3px; left: 10px;" Show Scores & Popularity
              .preference
                label.switch
                  input type="checkbox"
                  span.slider.round
                span style="position: relative; top: 3px; left: 10px;" Show "Why Match" &trade;
              p Sources:
              .preference
                label.switch
                  input type="checkbox" checked="true"
                  span.slider.round
                span style="position: relative; top: 3px; left: 10px;" Flight Data
              .preference
                label.switch
                  input type="checkbox" checked="true"
                  span.slider.round
                span style="position: relative; top: 3px; left: 10px;" eCommerce Sales
              .preference
                label.switch
                  input type="checkbox" checked="true"
                  span.slider.round
                span style="position: relative; top: 3px; left: 10px;" Web Logs
              p Logo:
              .preference
                = select_tag(:logo, options_for_select([["Elastic", "elastic"], ["Custom", "custom"]], cookies.encrypted[:logo]), id: "logo-select", class: "form-control", style: "width: 200px;")
          p style="margin-top: 18px; font-size: 0.8em;"
            a.close-support style="opacity: 0.8;" Close
        .support-form
          .form-container.form-open
            .form
              /.input
                input#subject/
                label for="subject" Subject
              .input
                textarea#message
                label for="message" How can we help?
              .input
                input#email
                label for="email" Email Address
              .form-actions
                span.button Send
                span style="margin-left: 8px;"
                  a.close-support Cancel
            .loader
              svg.uil-ring-alt height="194px" preserveaspectratio="xMidYMid" viewbox=("0 0 100 100") width="194px" xmlns="http://www.w3.org/2000/svg" 
                rect.bk fill="none" height="100" width="100" x="0" y="0" 
                circle cx="50" cy="50" fill="none" r="40" stroke="none" stroke-linecap="round" stroke-width="10" 
                circle cx="50" cy="50" fill="none" r="40" stroke="#258bf8" stroke-linecap="round" stroke-width="6" 
                  animate attributename="stroke-dashoffset" dur="2s" from="0" repeatcount="indefinite" to="502" 
                  animate attributename="stroke-dasharray" dur="2s" repeatcount="indefinite" values=("150.6 100.4;1 250;150.6 100.4") 
            .thanks
              h2.title Thank you for getting in touch
              p Our Search Team will review your request shortly.
              a.close-support href="#" Close